### PR TITLE
fix doc for messenger instead of message

### PR DESCRIPTION
**Pull request by soyuka**

### CODE REVIEW

**Comment by soyuka** [comment]
WDYT about proposing the alpine version of rabbitmq instead of the default?

**Review by sroze — APPROVED** [review]

**Comment by sroze** [comment]
> WDYT about proposing the alpine version of rabbitmq instead of the default?

What's the real advantage? :)

**Comment by soyuka** [comment]
Much smaller image haha

yeah here we're running on poor adsl connection, every byte matters

**Comment by sroze** [comment]
Does it include the management user interface?

**Comment by soyuka** [comment]
I guess so, hub website isn't loading to me right now (as usual) but I think that the image is the same only baseos is different:

https://hub.docker.com/_/rabbitmq/
```
docker run --rm -d --hostname localhost --name rabbit rabbitmq:3.7-rc-alpine
```

**Comment by sroze** [comment]
I guess the tag `3.7.4-management-alpine` would do it.

**Comment by sroze** [comment]
Thank you @soyuka.

**Pull request merged**
