### PR TITLE
Update namespace + fix cs issues

### PR DESCRIPTION
**Pull request by soyuka**

### CODE REVIEW

**Comment by soyuka** [comment]
should I add some tests? I read something about you having some behat tests?

**Review by sroze — CHANGES_REQUESTED** [review]
Great. Can you also change the tags in the `EnqueueBridgeExtension` ? `message.*` to `messenger.*` :)

**Comment by sroze** [comment]
> should I add some tests?

I'd say PHPUnit or PhpSpec tests are enough but if you want to invest some time in Behat tests, go for it 🌟

**Comment by soyuka** [comment]
I was refering to point 1 of your symfony PR:

> Tests are not in the PR as they were written in PhpSpec & Behat. If we decide to go forward with this approach, I'll translate them to PHPUnit.

Tests may come in another PR next week.

**Review by sroze — APPROVED** [review]
Very good, thank you 👍

**Pull request merged**
